### ISSUE TITLE
Needs XFCE Terminal support

### ISSUE THREAD

**Issue by racecar56** [tarakbumba/xdg-su#1]
Just add a
[ -z "$TERMINAL" ] && TERMINAL=$(which Terminal 2> /dev/null)
in the group of the lines that look similar to that.

**Comment by tarakbumba** [comment]
I' ll test and will add support for Terminal within next commit. Thanks for feedback and suggestion.

**Comment by tarakbumba** [comment]
Done! Please test it.

**Comment by racecar56** [comment]
It works.
